### ISSUE TITLE
Problem with NaNs 

### ISSUE THREAD

**Issue by rmalik203** [xtonyjiang/GNOVA#4]
Hi Tony,

I've been trying to use GNOVA in my project. For some of the sumstats files I'm using, I get the following error:

```
Traceback (most recent call last):
  File "gnova.py", line 86, in <module>
    pipeline(parser.parse_args())
  File "gnova.py", line 47, in pipeline
    out = calculate(gwas_snps, ld_scores, annots, N1, N2)
  File "/Volumes/BD/GNOVA/calculate.py", line 72, in calculate
    m1 = linear_model.LinearRegression().fit(ld_scores, pd.DataFrame((Z_x) ** 2), sample_weight=w1)
  File "/Volumes/Users/Library/Python/2.7/lib/python/site-packages/sklearn/linear_model/base.py", line 458, in fit
    y_numeric=True, multi_output=True)
  File "/Volumes/Users/Library/Python/2.7/lib/python/site-packages/sklearn/utils/validation.py", line 750, in check_X_y
    dtype=None)
  File "/Volumes/Users/Library/Python/2.7/lib/python/site-packages/sklearn/utils/validation.py", line 568, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Volumes/Users/Library/Python/2.7/lib/python/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

I tracked it down to the prep.py, where the 

`df = pd.merge(bim, dfs[1], on=['SNP']).merge(dfs[0], on=['SNP'])`

produces "NaN". I think this shouldn't be the case. Could this be a matter of the pandas version used?
My workaround was to introduce a

`df.dropna(inplace=True)`

but I don't think that's how it's meant to be.

Rainer

**Comment by daghli** [comment]
Getting same error.

**Comment by ShiqiangCheng** [comment]
Getting same error

**Comment by polpett** [comment]
idem

**Comment by polpett** [comment]
have you found a way to figure out this issue?

**Comment by daghli** [comment]
Manually remove the NAs from the munged sumstats file!

**Comment by polpett** [comment]
> Manually remove the NAs from the munged sumstats file!

Dear daghli, dear all, I have applied a filter based on the expected ranges for each column in bash. But, how can I be sure that I have removed all the ANs from the munged sumstats file? Could you suggest a script to use for this purpose?

**Comment by daghli** [comment]
I would recommend loading into R and trying something like:

library(data.table)
df<-fread("your_data",header=TRUE)
df<-na.omit(df)
write.table(df,"your_data_na_filtered",quote=FALSE,sep="\t",col.names=TRUE,row.names=FALSE)

________________________________

**Comment by QuanHongLiu** [comment]
I really recommend using this script, because there is no need to use R, pass parameters to it, or anything troublesome.
zcat /root/ldsc/sum_use/WBC_snplist.txt.sumstats.gz | awk 'NF==5' - | gzip > /root/GNOVA/sum_use_filter_NA/WBC_snplist.txt.sumstats.gz

**Comment by YaoJie224** [comment]
> I really recommend using this script, because there is no need to use R, pass parameters to it, or anything troublesome.我强烈推荐使用这个脚本，因为它不需要使用 R 语言，不需要向其传递参数，也不需要进行任何麻烦的操作。 zcat /root/ldsc/sum_use/WBC_snplist.txt.sumstats.gz | awk 'NF==5' - | gzip > /root/GNOVA/sum_use_filter_NA/WBC_snplist.txt.sumstats.gz

Yes, it is necessary to remove the missing rows first.
